### PR TITLE
Fixes #104. Now it's possible to type on remote machine and works sim…

### LINKED ISSUE #104: (Keymap?) issue in Jitsi remote screen
I discussed this on the Jitsi mailing lists and the link to that discussion is: http://lists.jitsi.org/pipermail/users/2014-February/006394.html

I am seeing an issue with typing in a remote screen session over Jitsi. While I can see the screen of the other party, move the mouse and make simple inputs, special keys do not work properly. In particular, pressing backspace or enter in a terminal window or using the backspace key is broken.
- Backspace triggers H (Ctrl-H),
- Enter triggers J (Ctrl-J)

and I see both keystrokes as h and j in the terminal, telling me the Ctrl switch was not transferred.

On a side note, pressing Enter (triggering j in the remote terminal) switches to the previous tab in the local Jitsi ;) ...

(Issue migrated from https://trac.jitsi.org/ticket/1277)

### PR DESCRIPTION
**Pull request by GNUDimarik**
Now it's possible to type on remote machine and works simple navigation such as backspace, enter and arrow keys.
Please review and let me know your opinions.
Sorry I'm tired after working day and before I made pull request in wrong issue (#135).
This one has right target

### CODE REVIEW

**Comment by GNUDimarik** [comment]
Will update the pull request soon since I have working better fix.
But I have also one question: keyboard events was grabbed because DTMFHandler tries to send us DTMF code and now I ignore this in renderer which can know when remote control on other side is enabled. But sound is still plays. From other side this is right place because we can have someone else on the call and that peer should handle DTMF since he doesn't enable remote control (as example) on his side.
So what do you think current solution is acceptable at least as start point?
Will provide the code a little later when I'll have feedback from QA.
Just I think deep testing may show us additional issues ...

File: src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingMouseAndKeyboardListener.java [hunk 1]
```diff
@@ -22,19 +22,22 @@
...
  */
 public class DesktopSharingMouseAndKeyboardListener
-    implements RemoteControlListener,
-               KeyListener,
-               MouseListener,
-               MouseMotionListener
+        implements RemoteControlListener,
+        KeyListener,
+        MouseListener,
+        MouseMotionListener
```
Comment (ibauersachs) [inline src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingMouseAndKeyboardListener.java]: Please avoid unnecessary changes

Comment (GNUDimarik) [reply src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingMouseAndKeyboardListener.java]: Ok. Thanks. WIll do

**Comment by GNUDimarik** [comment]
Please don't merge this until I didn't update the commit

File: src/net/java/sip/communicator/impl/hid/HIDServiceImpl.java [hunk 2]
```diff
@@ -77,19 +77,19 @@ protected HIDServiceImpl()
      */
     public void keyPress(int keycode)
     {
-        if(OSUtils.IS_WINDOWS || OSUtils.IS_MAC)
-        {
+        //if(OSUtils.IS_WINDOWS || OSUtils.IS_MAC)
```
Comment (GNUDimarik) [inline src/net/java/sip/communicator/impl/hid/HIDServiceImpl.java]: I decided to comment this code because if we work with Ctrl, Shift and Alt like with modifiers only we can't handle hotkeys like Ctrl+Shif+Left(Right) etc

File: src/net/java/sip/communicator/impl/gui/main/call/DTMFHandler.java [hunk 3]
```diff
@@ -227,6 +227,11 @@
      */
     public static final String DTMF_TONE_PREFIX = "DTMFTone.";
 
+    /**
+     * True if sending DTMF tone is enabled
+     */
+    private static boolean sendDTMFTone = true;
```
Comment (ibauersachs) [inline src/net/java/sip/communicator/impl/gui/main/call/DTMFHandler.java]: This must be specific to a call and thus cannot be static.

File: src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingMouseAndKeyboardListener.java [hunk 4]
```diff
@@ -244,6 +250,7 @@ public void remoteControlGranted(RemoteControlGrantedEvent event)
         {
             if(videoComponent != null)
             {
+                DTMFHandler.enableSendingDTMFTone(false);
```
Comment (ibauersachs) [inline src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingMouseAndKeyboardListener.java]: You can enable/disable the DTMFHandler by adding methods to CallPeerRenderer and get the associated renderer via
`CallManager.getActiveCallContainer(getCallPeer().getCall()).getCurrentCallRenderer().getCallPeerRenderer(getCallPeer())` or you can pass it down into the constructor of `DesktopSharingMouseAndKeyboardListener`.

File: src/net/java/sip/communicator/impl/hid/HIDServiceImpl.java (hunk 2 above)
Comment (ibauersachs) [reply src/net/java/sip/communicator/impl/hid/HIDServiceImpl.java]: Did you test this on all platforms, i.e. Linux, Mac and Windows?
If the code isn't needed anymore, remove it instead of leaving it commente.d

**Comment by GNUDimarik** [comment]
@ibauersachs 
Tested under Mac and it's not bad but I think cooperation between mac and other systems requires some additional work. Shift works fine and typing too. But when I got remote control on Mac from windows I expect Ctrl+C will copy to clipboard but now it doesn't work because Mac has another keys configuration. I think we need emulate this behaviour. And the same vise wersa. Mac user expects something from his kbd when he controlls windows machine. So I think we should finish this and next back to this pull request.

**Comment by GNUDimarik** [comment]
Testing under linux will possible after fixing this issue: https://github.com/jitsi/jitsi/issues/245

**Comment by GNUDimarik** [comment]
I got it. But anyway there should be way for making possible to conveniently work with remote control from windows to mac and wise versa. The both windows and mac are most popular platrorms and I think this case is real.
let's add a separate issue for that. What do you think?
By this issue: after testing under linux I'll fix the comments.

**Comment by GNUDimarik** [comment]
Under linux the same behaviour like under windows. Tested between Ubuntu 16 and Windows 10

**Comment by GNUDimarik** [comment]
@ibauersachs please check ammended commit
