### PR TITLE
Fixes #521 by adding sharing region before staring remote control and destroys origin when sharing is disabled

### LINKED ISSUE #521: Wrong mouse coordinates when remote control enabled during part screen sharing session
When you trying to share part of your screen you should enable remote control. After please try to mouse move and you will be able to notice cursor position is wrong.
Will make pull request with fix for this soon

### PR DESCRIPTION
**Pull request by GNUDimarik**
Here is the build for testing: https://www.dropbox.com/s/h3pj3qdcqno9u3v/jitsi-2.11.0-x86.exe?dl=0

### CODE REVIEW

File: src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingFrame.java [hunk 1]
```diff
@@ -528,13 +528,16 @@ public void actionPerformed(ActionEvent e)
 
                     frame.dispose();
 
-                    if (call != null)
+                    if (call != null) {
```
Comment (ibauersachs) [inline src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingFrame.java]: Formatting

File: src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingFrame.java [hunk 2]
```diff
@@ -249,7 +249,7 @@ private static void addDesktopSharingListener(final Call call, JFrame frame)
     {
         OperationSetVideoTelephony videoTelephony
             = call.getProtocolProvider().getOperationSet(
-                    OperationSetVideoTelephony.class);
+                OperationSetDesktopSharingServer.class);
```
Comment (ibauersachs) [inline src/net/java/sip/communicator/impl/gui/main/call/DesktopSharingFrame.java]: This change seems unneccessary.
